=== jed9h3/BZU_CS_Projects/webServicesTask1/students.xsd
<?xml version="1.1" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="students">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="student" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="id" type="xs:int" />
                            <xs:element name="name" type="xs:string" />
                            <xs:element name="dob" type="xs:date" />
                            <xs:element name="avg" type="xs:float" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== jed9h3/BZU_CS_Projects/webServicesTask1/students.xml
<?xml version="1.1" encoding="UTF-8"?>
<students xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="students.xsd">
    <student>
        <id>1202940</id>
        <name>Majed Alghoul</name>
        <dob>2002-03-02</dob>
        <avg>78</avg>
    </student>
    <student>
        <id>1202941</id>
        <name>Ahmad Kalil</name>
        <dob>2002-08-08</dob>
        <avg>75</avg>
    </student>
    <student>
        <id>1202942</id>
        <name>Tariq Farid</name>
        <dob>2002-05-03</dob>
        <avg>90</avg>
    </student>
</students>
